config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: cmp-datamart-dbpgs-dev
      host: cmp-datamart-dbpgs-dev.cmp-datamart-pgs-dev.svc.cluster.local
      pass: P9Vt7nhE4LgjV40
      port: 5432
      schema: analytics
      threads: 8
      type: postgres
      user: postgres
  target: prod
